Magice\Bundle\ClientUserBundle\Entity\User:
    type: entity
    table: mg_user
    indexes:
        JOYPRICE_ID:
            columns: [joyprice_id]
    id:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
    fields:
        joypriceId:
            type: integer
            unique: true
            column: joyprice_id

        joypriceAccessToken:
            type: string
            length: 255
            column: joyprice_access_token

    lifecycleCallbacks: {  }
